browser=chrome
start-maximized=true
headless=false
disable-popup-blocking=true
disable-extensions=false
extension-path=extensions/webextensions-selenium-example.crx

baseUrl=https://demo.testarchitect.com/
timeout=9000